import LnProof.FloorConsts

/-! Generate `BiasCapNum.lean`: the tight bias-cap numerator
`biasCapNum = ⌊expNum 130 (BIASc·2²⁷) QS · 10⁶⁰ / (130!·QS¹³⁰)⌋`, the sharp lower
cap on `e^(BIASc·2²⁷/QS)` used by `capBLtight` and the error weights. Computed
from the model inputs (BIASc), so it tracks any bias change. Run with
`lake env lean GenErr1.lean` (after `lake build LnProof.FloorConsts`). -/

open LnExp LnFloor LnYul

#eval do
  let bcap := (LnExp.expNum 130 (BIASc * 2 ^ 27) QS * (10 ^ 18 * 10 ^ 42)) / (LnExp.fact 130 * QS ^ 130)
  IO.FS.writeFile "LnProof/BiasCapNum.lean"
    s!"/-! Generated by GenErr1 (lake env lean GenErr1.lean): the tight bias-cap\nnumerator BIASCAPNUM, the sharp lower cap on e^(BIASc·2^27/QS) used by\ncapBLtight and the error weights. -/\nnamespace LnFloorCert\n\ndef biasCapNum : Nat := {bcap}\n\nend LnFloorCert\n"
  IO.println s!"BiasCapNum written: {bcap}"
