name = "Sqrt512Proof"
version = "0.1.0"
defaultTargets = ["Sqrt512Proof"]
packagesDir = "../../yul/.lake/packages"

[[lean_lib]]
name = "Sqrt512Proof"

[[require]]
name = "FormalYul"
path = "../../yul"

[[require]]
name = "SqrtProof"
path = "../SqrtProof"
