name = "Cbrt512Proof"
version = "0.1.0"
defaultTargets = ["Cbrt512Proof"]
packagesDir = "../../yul/.lake/packages"

[[lean_lib]]
name = "Cbrt512Proof"

[[require]]
name = "FormalYul"
path = "../../yul"

[[require]]
name = "CbrtProof"
path = "../CbrtProof"
