name = "FormalYul"
version = "0.1.0"
defaultTargets = ["FormalYul"]

[[lean_lib]]
name = "FormalYul"

[[lean_exe]]
name = "yul_importer"
root = "YulImporter"

[[require]]
name = "evmyul"
path = "../../lib/EVMYulLean"
