import FormalYul

namespace YulImporter

inductive ModelKind where
  | sqrt
  | sqrt512
  | cbrt
  | cbrt512
  | ln
  deriving DecidableEq, Repr

namespace ModelKind

def parse : String → Option ModelKind
  | "sqrt" => some .sqrt
  | "sqrt512" => some .sqrt512
  | "cbrt" => some .cbrt
  | "cbrt512" => some .cbrt512
  | "ln" => some .ln
  | _ => none

def namespaceName : ModelKind → String
  | .sqrt => "SqrtYul"
  | .sqrt512 => "Sqrt512Yul"
  | .cbrt => "CbrtYul"
  | .cbrt512 => "Cbrt512Yul"
  | .ln => "LnYul"

def requiredMarkers : ModelKind → List String
  | .sqrt => ["object ", "deployed", "function fun__sqrt", "function fun_sqrt", "function fun_sqrtUp", "clz("]
  | .sqrt512 => ["object ", "deployed", "wrap_sqrt512", "wrap_osqrtUp", "function fun__sqrt", "_sqrt_baseCase", "mulmod", "clz("]
  | .cbrt => ["object ", "deployed", "function fun__cbrt", "function fun_cbrt", "function fun_cbrtUp", "clz("]
  | .cbrt512 => ["object ", "deployed", "wrap_cbrt512", "wrap_cbrtUp512", "function fun__cbrt", "_cbrt_baseCase", "mulmod", "clz("]
  | .ln => ["object ", "deployed", "function fun_lnWad", "function fun_lnWadToRay", "sdiv", "clz("]

def selectorCases : ModelKind → List String
  | .sqrt => ["0x5b29048a", "0x65c9cba1"]
  | .sqrt512 => ["0x3f51628a", "0x996e33a4"]
  | .cbrt => ["0x56df2b56", "0x29f2f4f1"]
  | .cbrt512 => ["0xa83a5c08", "0x7c0352fc"]
  | .ln => ["0xef102248", "0x31d42abd"]

def functionPrefixes : ModelKind → List String
  | .sqrt =>
      ["external_fun_wrap_sqrt_", "external_fun_wrap_sqrtUp_",
       "fun_wrap_sqrt_", "fun_wrap_sqrtUp_", "fun_sqrt_", "fun_sqrtUp_", "fun__sqrt_"]
  | .sqrt512 =>
      ["external_fun_wrap_sqrt512_", "external_fun_wrap_osqrtUp_",
       "fun_wrap_sqrt512_", "fun_wrap_osqrtUp_",
       "fun__sqrt_baseCase_", "fun__sqrt_karatsubaQuotient_",
       "fun__sqrt_correction_", "fun__sqrt_babylonianStep_"]
  | .cbrt =>
      ["external_fun_wrap_cbrt_", "external_fun_wrap_cbrtUp_",
       "fun_wrap_cbrt_", "fun_wrap_cbrtUp_", "fun_cbrt_", "fun_cbrtUp_", "fun__cbrt_"]
  | .cbrt512 =>
      ["external_fun_wrap_cbrt512_", "external_fun_wrap_cbrtUp512_",
       "fun_wrap_cbrt512_", "fun_wrap_cbrtUp512_",
       "fun__cbrt_baseCase_", "fun__cbrt_karatsubaQuotient_",
       "fun__cbrt_quadraticCorrection_", "fun__cbrt_newtonRaphsonStep_"]
  | .ln =>
      ["external_fun_wrap_lnWad_", "external_fun_wrap_lnWadToRay_",
       "fun_wrap_lnWad_", "fun_wrap_lnWadToRay_", "fun_lnWad_", "fun_lnWadToRay_"]

end ModelKind

structure Options where
  kind : Option ModelKind := none
  output : Option String := none

partial def parseArgs : List String → Options → Except String Options
  | [], opts => .ok opts
  | "--kind" :: value :: rest, opts =>
      match ModelKind.parse value with
      | some kind => parseArgs rest { opts with kind := some kind }
      | none => .error s!"unknown model kind: {value}"
  | "--output" :: value :: rest, opts =>
      parseArgs rest { opts with output := some value }
  | value :: rest, opts =>
      match opts.kind, ModelKind.parse value with
      | none, some kind => parseArgs rest { opts with kind := some kind }
      | _, _ => .error s!"unexpected argument: {value}"

def templateSqrt : String :=
"import Init

namespace SqrtYul

/-- Auto-generated from solc Yul IR for Sqrt.lean. -/
-- Source: src/vendor/Sqrt.sol
-- Modeled functions: _sqrt, sqrt, sqrtUp
-- Generated by: lake exe yul_importer
-- Modeled opcodes/Yul builtins: SHR, SUB, CLZ, ADD, SHL, DIV, LT, MUL, GT

def WORD_MOD : Nat := 2 ^ 256

def u256 (x : Nat) : Nat :=
  x % WORD_MOD

def evmAdd (a b : Nat) : Nat :=
  u256 (u256 a + u256 b)

def evmSub (a b : Nat) : Nat :=
  u256 (u256 a + WORD_MOD - u256 b)

def evmMul (a b : Nat) : Nat :=
  u256 (u256 a * u256 b)

def evmDiv (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  if bb = 0 then 0 else aa / bb

def evmMod (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  if bb = 0 then 0 else aa % bb

def evmNot (a : Nat) : Nat :=
  WORD_MOD - 1 - u256 a

def evmOr (a b : Nat) : Nat :=
  u256 a ||| u256 b

def evmAnd (a b : Nat) : Nat :=
  u256 a &&& u256 b

def evmByte (index value : Nat) : Nat :=
  let i := u256 index
  let v := u256 value
  if i < 32 then (v / 2 ^ (8 * (31 - i))) % 256 else 0

def evmEq (a b : Nat) : Nat :=
  if u256 a = u256 b then 1 else 0

def evmIszero (a : Nat) : Nat :=
  if u256 a = 0 then 1 else 0

def evmShl (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if s < 256 then u256 (v * 2 ^ s) else 0

def evmShr (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if s < 256 then v / 2 ^ s else 0

def evmClz (value : Nat) : Nat :=
  let v := u256 value
  if v = 0 then 256 else 255 - Nat.log2 v

def evmLt (a b : Nat) : Nat :=
  if u256 a < u256 b then 1 else 0

def evmGt (a b : Nat) : Nat :=
  if u256 a > u256 b then 1 else 0

def evmMulmod (a b n : Nat) : Nat :=
  let aa := u256 a; let bb := u256 b; let nn := u256 n
  if nn = 0 then 0 else (aa * bb) % nn

def evmSdiv (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  let na := decide (2 ^ 255 ≤ aa)
  let nb := decide (2 ^ 255 ≤ bb)
  let ma := if na then WORD_MOD - aa else aa
  let mb := if nb then WORD_MOD - bb else bb
  if bb = 0 then 0
  else if na = nb then u256 (ma / mb)
  else u256 (WORD_MOD - ma / mb)

def evmSar (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if 2 ^ 255 ≤ v then
    if 256 ≤ s then WORD_MOD - 1
    else WORD_MOD - 1 - (WORD_MOD - 1 - v) / 2 ^ s
  else if 256 ≤ s then 0
  else v / 2 ^ s

def evmSlt (a b : Nat) : Nat :=
  if (u256 a + 2 ^ 255) % WORD_MOD < (u256 b + 2 ^ 255) % WORD_MOD then 1 else 0

def evmSgt (a b : Nat) : Nat :=
  if (u256 b + 2 ^ 255) % WORD_MOD < (u256 a + 2 ^ 255) % WORD_MOD then 1 else 0

def normAdd (a b : Nat) : Nat := a + b

def normSub (a b : Nat) : Nat := a - b

def normMul (a b : Nat) : Nat := a * b

def normDiv (a b : Nat) : Nat := a / b

def normMod (a b : Nat) : Nat := a % b

def normNot (a : Nat) : Nat := WORD_MOD - 1 - a

def normOr (a b : Nat) : Nat := a ||| b

def normAnd (a b : Nat) : Nat := a &&& b

def normByte (index value : Nat) : Nat :=
  if index < 32 then (value / 2 ^ (8 * (31 - index))) % 256 else 0

def normEq (a b : Nat) : Nat :=
  if a = b then 1 else 0

def normIszero (a : Nat) : Nat :=
  if a = 0 then 1 else 0

def normShl (shift value : Nat) : Nat := value <<< shift

def normShr (shift value : Nat) : Nat := value / 2 ^ shift

def normClz (value : Nat) : Nat :=
  if value = 0 then 256 else 255 - Nat.log2 value

def normLt (a b : Nat) : Nat :=
  if a < b then 1 else 0

def normGt (a b : Nat) : Nat :=
  if a > b then 1 else 0

def normMulmod (a b n : Nat) : Nat :=
  if n = 0 then 0 else (a * b) % n

def normSdiv (a b : Nat) : Nat :=
  let na := decide (2 ^ 255 ≤ a % WORD_MOD)
  let nb := decide (2 ^ 255 ≤ b % WORD_MOD)
  let ma := if na then WORD_MOD - a % WORD_MOD else a % WORD_MOD
  let mb := if nb then WORD_MOD - b % WORD_MOD else b % WORD_MOD
  if b % WORD_MOD = 0 then 0
  else if na = nb then ma / mb % WORD_MOD
  else (WORD_MOD - ma / mb) % WORD_MOD

def normSar (shift value : Nat) : Nat :=
  let s := shift % WORD_MOD
  let v := value % WORD_MOD
  if 2 ^ 255 ≤ v then
    if 256 ≤ s then WORD_MOD - 1
    else WORD_MOD - 1 - (WORD_MOD - 1 - v) / 2 ^ s
  else if 256 ≤ s then 0
  else v / 2 ^ s

def normSlt (a b : Nat) : Nat :=
  if (a % WORD_MOD + 2 ^ 255) % WORD_MOD < (b % WORD_MOD + 2 ^ 255) % WORD_MOD then 1
  else 0

def normSgt (a b : Nat) : Nat :=
  if (b % WORD_MOD + 2 ^ 255) % WORD_MOD < (a % WORD_MOD + 2 ^ 255) % WORD_MOD then 1
  else 0

/-- Opcode-faithful auto-generated model of `_sqrt` with uint256 EVM semantics. -/
def model_sqrt_evm (x : Nat) : Nat :=
  let x := u256 x
  let z_1 := evmShr (1) (evmSub (256) (evmClz (x)))
  let z_2 := evmShr (1) (evmAdd (evmShl (z_1) (1)) (evmShr (z_1) (x)))
  let z_3 := evmShr (1) (evmAdd (z_2) (evmDiv (x) (z_2)))
  let z_4 := evmShr (1) (evmAdd (z_3) (evmDiv (x) (z_3)))
  let z_5 := evmShr (1) (evmAdd (z_4) (evmDiv (x) (z_4)))
  let z_6 := evmShr (1) (evmAdd (z_5) (evmDiv (x) (z_5)))
  let z_7 := evmShr (1) (evmAdd (z_6) (evmDiv (x) (z_6)))
  z_7

/-- Normalized auto-generated model of `_sqrt` on Nat arithmetic. -/
def model_sqrt (x : Nat) : Nat :=
  let z_1 := normShr (1) (normSub (256) (normClz (x)))
  let z_2 := normShr (1) (normAdd (normShl (z_1) (1)) (normShr (z_1) (x)))
  let z_3 := normShr (1) (normAdd (z_2) (normDiv (x) (z_2)))
  let z_4 := normShr (1) (normAdd (z_3) (normDiv (x) (z_3)))
  let z_5 := normShr (1) (normAdd (z_4) (normDiv (x) (z_4)))
  let z_6 := normShr (1) (normAdd (z_5) (normDiv (x) (z_5)))
  let z_7 := normShr (1) (normAdd (z_6) (normDiv (x) (z_6)))
  z_7

/-- Opcode-faithful auto-generated model of `sqrt` with uint256 EVM semantics. -/
def model_sqrt_floor_evm (x : Nat) : Nat :=
  let x := u256 x
  let expr_22 := model_sqrt_evm (x)
  let z_2 := evmSub (expr_22) (evmLt (evmDiv (x) (expr_22)) (expr_22))
  z_2

/-- Normalized auto-generated model of `sqrt` on Nat arithmetic. -/
def model_sqrt_floor (x : Nat) : Nat :=
  let expr_22 := model_sqrt (x)
  let z_2 := normSub (expr_22) (normLt (normDiv (x) (expr_22)) (expr_22))
  z_2

/-- Opcode-faithful auto-generated model of `sqrtUp` with uint256 EVM semantics. -/
def model_sqrt_up_evm (x : Nat) : Nat :=
  let x := u256 x
  let expr_38 := model_sqrt_evm (x)
  let zz := evmMul (expr_38) (expr_38)
  let z_2 := evmAdd (evmGt (evmLt (zz) (x)) (evmLt (zz) (expr_38))) (expr_38)
  z_2

/-- Normalized auto-generated model of `sqrtUp` on Nat arithmetic. -/
def model_sqrt_up (x : Nat) : Nat :=
  let expr_38 := model_sqrt (x)
  let zz := normMul (expr_38) (expr_38)
  let z_2 := normAdd (normGt (normLt (zz) (x)) (normLt (zz) (expr_38))) (expr_38)
  z_2

end SqrtYul
"

def templateSqrt512 : String :=
"import Init

namespace Sqrt512Yul

/-- Auto-generated from solc Yul IR for 512Math sqrt. -/
-- Source: src/utils/512Math.sol
-- Modeled functions: _sqrt_babylonianStep, _sqrt_baseCase, _sqrt_karatsubaQuotient, _sqrt_correction, _sqrt, sqrt, sqrtUp, wrap_sqrt512, wrap_osqrtUp
-- Generated by: lake exe yul_importer
-- Modeled opcodes/Yul builtins: DIV, ADD, SHR, LT, SUB, MUL, OR, SHL, MOD, EQ, AND, CLZ, GT, ISZERO, MULMOD

def WORD_MOD : Nat := 2 ^ 256

def u256 (x : Nat) : Nat :=
  x % WORD_MOD

def evmAdd (a b : Nat) : Nat :=
  u256 (u256 a + u256 b)

def evmSub (a b : Nat) : Nat :=
  u256 (u256 a + WORD_MOD - u256 b)

def evmMul (a b : Nat) : Nat :=
  u256 (u256 a * u256 b)

def evmDiv (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  if bb = 0 then 0 else aa / bb

def evmMod (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  if bb = 0 then 0 else aa % bb

def evmNot (a : Nat) : Nat :=
  WORD_MOD - 1 - u256 a

def evmOr (a b : Nat) : Nat :=
  u256 a ||| u256 b

def evmAnd (a b : Nat) : Nat :=
  u256 a &&& u256 b

def evmByte (index value : Nat) : Nat :=
  let i := u256 index
  let v := u256 value
  if i < 32 then (v / 2 ^ (8 * (31 - i))) % 256 else 0

def evmEq (a b : Nat) : Nat :=
  if u256 a = u256 b then 1 else 0

def evmIszero (a : Nat) : Nat :=
  if u256 a = 0 then 1 else 0

def evmShl (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if s < 256 then u256 (v * 2 ^ s) else 0

def evmShr (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if s < 256 then v / 2 ^ s else 0

def evmClz (value : Nat) : Nat :=
  let v := u256 value
  if v = 0 then 256 else 255 - Nat.log2 v

def evmLt (a b : Nat) : Nat :=
  if u256 a < u256 b then 1 else 0

def evmGt (a b : Nat) : Nat :=
  if u256 a > u256 b then 1 else 0

def evmMulmod (a b n : Nat) : Nat :=
  let aa := u256 a; let bb := u256 b; let nn := u256 n
  if nn = 0 then 0 else (aa * bb) % nn

def evmSdiv (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  let na := decide (2 ^ 255 ≤ aa)
  let nb := decide (2 ^ 255 ≤ bb)
  let ma := if na then WORD_MOD - aa else aa
  let mb := if nb then WORD_MOD - bb else bb
  if bb = 0 then 0
  else if na = nb then u256 (ma / mb)
  else u256 (WORD_MOD - ma / mb)

def evmSar (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if 2 ^ 255 ≤ v then
    if 256 ≤ s then WORD_MOD - 1
    else WORD_MOD - 1 - (WORD_MOD - 1 - v) / 2 ^ s
  else if 256 ≤ s then 0
  else v / 2 ^ s

def evmSlt (a b : Nat) : Nat :=
  if (u256 a + 2 ^ 255) % WORD_MOD < (u256 b + 2 ^ 255) % WORD_MOD then 1 else 0

def evmSgt (a b : Nat) : Nat :=
  if (u256 b + 2 ^ 255) % WORD_MOD < (u256 a + 2 ^ 255) % WORD_MOD then 1 else 0

def normAdd (a b : Nat) : Nat := a + b

def normSub (a b : Nat) : Nat := a - b

def normMul (a b : Nat) : Nat := a * b

def normDiv (a b : Nat) : Nat := a / b

def normMod (a b : Nat) : Nat := a % b

def normNot (a : Nat) : Nat := WORD_MOD - 1 - a

def normOr (a b : Nat) : Nat := a ||| b

def normAnd (a b : Nat) : Nat := a &&& b

def normByte (index value : Nat) : Nat :=
  if index < 32 then (value / 2 ^ (8 * (31 - index))) % 256 else 0

def normEq (a b : Nat) : Nat :=
  if a = b then 1 else 0

def normIszero (a : Nat) : Nat :=
  if a = 0 then 1 else 0

def normShl (shift value : Nat) : Nat := value <<< shift

def normShr (shift value : Nat) : Nat := value / 2 ^ shift

def normClz (value : Nat) : Nat :=
  if value = 0 then 256 else 255 - Nat.log2 value

def normLt (a b : Nat) : Nat :=
  if a < b then 1 else 0

def normGt (a b : Nat) : Nat :=
  if a > b then 1 else 0

def normMulmod (a b n : Nat) : Nat :=
  if n = 0 then 0 else (a * b) % n

def normSdiv (a b : Nat) : Nat :=
  let na := decide (2 ^ 255 ≤ a % WORD_MOD)
  let nb := decide (2 ^ 255 ≤ b % WORD_MOD)
  let ma := if na then WORD_MOD - a % WORD_MOD else a % WORD_MOD
  let mb := if nb then WORD_MOD - b % WORD_MOD else b % WORD_MOD
  if b % WORD_MOD = 0 then 0
  else if na = nb then ma / mb % WORD_MOD
  else (WORD_MOD - ma / mb) % WORD_MOD

def normSar (shift value : Nat) : Nat :=
  let s := shift % WORD_MOD
  let v := value % WORD_MOD
  if 2 ^ 255 ≤ v then
    if 256 ≤ s then WORD_MOD - 1
    else WORD_MOD - 1 - (WORD_MOD - 1 - v) / 2 ^ s
  else if 256 ≤ s then 0
  else v / 2 ^ s

def normSlt (a b : Nat) : Nat :=
  if (a % WORD_MOD + 2 ^ 255) % WORD_MOD < (b % WORD_MOD + 2 ^ 255) % WORD_MOD then 1
  else 0

def normSgt (a b : Nat) : Nat :=
  if (b % WORD_MOD + 2 ^ 255) % WORD_MOD < (a % WORD_MOD + 2 ^ 255) % WORD_MOD then 1
  else 0

/-- Opcode-faithful auto-generated model of `_sqrt_babylonianStep` with uint256 EVM semantics. -/
def model_bstep_evm (x r : Nat) : Nat :=
  let x := u256 x
  let r := u256 r
  let expr_4315 := evmDiv (x) (r)
  let expr_4317 := evmAdd (expr_4315) (r)
  let expr_4319 := evmShr (1) (expr_4317)
  let var__4310_1 := expr_4319
  var__4310_1

/-- Normalized auto-generated model of `_sqrt_babylonianStep` on Nat arithmetic. -/
def model_bstep (x r : Nat) : Nat :=
  let expr_4315 := normDiv (x) (r)
  let expr_4317 := normAdd (expr_4315) (r)
  let expr_4319 := normShr (1) (expr_4317)
  let var__4310_1 := expr_4319
  var__4310_1

/-- Opcode-faithful auto-generated model of `_sqrt_baseCase` with uint256 EVM semantics. -/
def model_innerSqrt_evm (x_hi : Nat) : Nat × Nat :=
  let x_hi := u256 x_hi
  let expr_4341 := model_bstep_evm (x_hi) (240615969168004511545033772477625056927)
  let expr_4348 := model_bstep_evm (x_hi) (expr_4341)
  let expr_4355 := model_bstep_evm (x_hi) (expr_4348)
  let expr_4362 := model_bstep_evm (x_hi) (expr_4355)
  let expr_4369 := model_bstep_evm (x_hi) (expr_4362)
  let expr_4376 := model_bstep_evm (x_hi) (expr_4369)
  let expr_4385 := evmDiv (x_hi) (expr_4376)
  let expr_4387 := evmLt (expr_4385) (expr_4376)
  let expr_4388 := evmSub (expr_4376) (expr_4387)
  let r_hi_8 := expr_4388
  let res_1 := evmSub (x_hi) (evmMul (expr_4388) (expr_4388))
  (r_hi_8, res_1)

/-- Normalized auto-generated model of `_sqrt_baseCase` on Nat arithmetic. -/
def model_innerSqrt (x_hi : Nat) : Nat × Nat :=
  let expr_4341 := model_bstep (x_hi) (240615969168004511545033772477625056927)
  let expr_4348 := model_bstep (x_hi) (expr_4341)
  let expr_4355 := model_bstep (x_hi) (expr_4348)
  let expr_4362 := model_bstep (x_hi) (expr_4355)
  let expr_4369 := model_bstep (x_hi) (expr_4362)
  let expr_4376 := model_bstep (x_hi) (expr_4369)
  let expr_4385 := normDiv (x_hi) (expr_4376)
  let expr_4387 := normLt (expr_4385) (expr_4376)
  let expr_4388 := normSub (expr_4376) (expr_4387)
  let r_hi_8 := expr_4388
  let res_1 := normSub (x_hi) (normMul (expr_4388) (expr_4388))
  (r_hi_8, res_1)

/-- Opcode-faithful auto-generated model of `_sqrt_karatsubaQuotient` with uint256 EVM semantics. -/
def model_karatsubaQuotient_evm (res x_lo r_hi : Nat) : Nat × Nat :=
  let res := u256 res
  let x_lo := u256 x_lo
  let r_hi := u256 r_hi
  let n := evmOr (evmShl (128) (res)) (evmShr (128) (x_lo))
  let d := evmShl (1) (r_hi)
  let r_lo_1 := evmDiv (n) (d)
  let c := evmShr (128) (res)
  let res_out_1 := evmMod (n) (d)
  let (r_lo_2, res_out_2) := if (c) ≠ 0 then
      let r_lo_2 := evmAdd (r_lo_1) (evmDiv (115792089237316195423570985008687907853269984665640564039457584007913129639935) (d))
      let res_out_2 := evmAdd (res_out_1) (evmAdd (1) (evmMod (115792089237316195423570985008687907853269984665640564039457584007913129639935) (d)))
      let r_lo_3 := evmAdd (r_lo_2) (evmDiv (res_out_2) (d))
      let res_out_3 := evmMod (res_out_2) (d)
      (r_lo_3, res_out_3)
    else
      (r_lo_1, res_out_1)
  (r_lo_2, res_out_2)

/-- Normalized auto-generated model of `_sqrt_karatsubaQuotient` on Nat arithmetic. -/
def model_karatsubaQuotient (res x_lo r_hi : Nat) : Nat × Nat :=
  let n := normOr (normShl (128) (res)) (normShr (128) (x_lo))
  let d := normShl (1) (r_hi)
  let r_lo_1 := normDiv (n) (d)
  let c := normShr (128) (res)
  let res_out_1 := normMod (n) (d)
  let (r_lo_2, res_out_2) := if (c) ≠ 0 then
      let r_lo_2 := normAdd (r_lo_1) (normDiv (115792089237316195423570985008687907853269984665640564039457584007913129639935) (d))
      let res_out_2 := normAdd (res_out_1) (normAdd (1) (normMod (115792089237316195423570985008687907853269984665640564039457584007913129639935) (d)))
      let r_lo_3 := normAdd (r_lo_2) (normDiv (res_out_2) (d))
      let res_out_3 := normMod (res_out_2) (d)
      (r_lo_3, res_out_3)
    else
      (r_lo_1, res_out_1)
  (r_lo_2, res_out_2)

/-- Opcode-faithful auto-generated model of `_sqrt_correction` with uint256 EVM semantics. -/
def model_sqrtCorrection_evm (r_hi r_lo res x_lo : Nat) : Nat :=
  let r_hi := u256 r_hi
  let r_lo := u256 r_lo
  let res := u256 res
  let x_lo := u256 x_lo
  let expr_4426 := evmShl (128) (r_hi)
  let expr_4429 := evmAdd (expr_4426) (r_lo)
  let expr_4437 := evmShr (128) (res)
  let expr_4441 := evmShr (128) (r_lo)
  let expr_4443 := evmLt (expr_4437) (expr_4441)
  let expr_4448 := evmShr (128) (res)
  let expr_4452 := evmShr (128) (r_lo)
  let expr_4454 := evmEq (expr_4448) (expr_4452)
  let expr_4459 := evmShl (128) (res)
  let expr_4463 := evmAnd (x_lo) (340282366920938463463374607431768211455)
  let expr_4465 := evmOr (expr_4459) (expr_4463)
  let expr_4468 := evmMul (r_lo) (r_lo)
  let expr_4469 := evmLt (expr_4465) (expr_4468)
  let expr_4470 := evmAnd (expr_4454) (expr_4469)
  let expr_4471 := evmOr (expr_4443) (expr_4470)
  let expr_4472 := evmSub (expr_4429) (expr_4471)
  let r_2 := expr_4472
  r_2

/-- Normalized auto-generated model of `_sqrt_correction` on Nat arithmetic. -/
def model_sqrtCorrection (r_hi r_lo res x_lo : Nat) : Nat :=
  let expr_4426 := normShl (128) (r_hi)
  let expr_4429 := normAdd (expr_4426) (r_lo)
  let expr_4437 := normShr (128) (res)
  let expr_4441 := normShr (128) (r_lo)
  let expr_4443 := normLt (expr_4437) (expr_4441)
  let expr_4448 := normShr (128) (res)
  let expr_4452 := normShr (128) (r_lo)
  let expr_4454 := normEq (expr_4448) (expr_4452)
  let expr_4459 := normShl (128) (res)
  let expr_4463 := normAnd (x_lo) (340282366920938463463374607431768211455)
  let expr_4465 := normOr (expr_4459) (expr_4463)
  let expr_4468 := normMul (r_lo) (r_lo)
  let expr_4469 := normLt (expr_4465) (expr_4468)
  let expr_4470 := normAnd (expr_4454) (expr_4469)
  let expr_4471 := normOr (expr_4443) (expr_4470)
  let expr_4472 := normSub (expr_4429) (expr_4471)
  let r_2 := expr_4472
  r_2

/-- Opcode-faithful auto-generated model of `_sqrt` with uint256 EVM semantics. -/
def model_sqrt512_evm (x_hi x_lo : Nat) : Nat :=
  let x_hi := u256 x_hi
  let x_lo := u256 x_lo
  let expr_4490 := evmClz (x_hi)
  let expr_4500 := evmAnd (expr_4490) (254)
  let _tmp_388 := evmOr (evmShl (expr_4500) (x_hi)) (evmShr (evmSub (256) (expr_4500)) (x_lo))
  let _tmp_389 := evmShl (expr_4500) (x_lo)
  let expr_4506 := evmShr (1) (expr_4490)
  let expr_4514_component_1 := (model_innerSqrt_evm (_tmp_388)).1
  let expr_4514_component_2 := (model_innerSqrt_evm (_tmp_388)).2
  let expr_4526_component_1 := (model_karatsubaQuotient_evm (expr_4514_component_2) (_tmp_389) (expr_4514_component_1)).1
  let expr_4526_component_2 := (model_karatsubaQuotient_evm (expr_4514_component_2) (_tmp_389) (expr_4514_component_1)).2
  let expr_4535 := model_sqrtCorrection_evm (expr_4514_component_1) (expr_4526_component_1) (expr_4526_component_2) (_tmp_389)
  let expr_4540 := evmShr (expr_4506) (expr_4535)
  let r_2 := expr_4540
  r_2

/-- Normalized auto-generated model of `_sqrt` on Nat arithmetic. -/
def model_sqrt512 (x_hi x_lo : Nat) : Nat :=
  let expr_4490 := normClz (x_hi)
  let expr_4500 := normAnd (expr_4490) (254)
  let _tmp_388 := normOr (normShl (expr_4500) (x_hi)) (normShr (normSub (256) (expr_4500)) (x_lo))
  let _tmp_389 := normShl (expr_4500) (x_lo)
  let expr_4506 := normShr (1) (expr_4490)
  let expr_4514_component_1 := (model_innerSqrt (_tmp_388)).1
  let expr_4514_component_2 := (model_innerSqrt (_tmp_388)).2
  let expr_4526_component_1 := (model_karatsubaQuotient (expr_4514_component_2) (_tmp_389) (expr_4514_component_1)).1
  let expr_4526_component_2 := (model_karatsubaQuotient (expr_4514_component_2) (_tmp_389) (expr_4514_component_1)).2
  let expr_4535 := model_sqrtCorrection (expr_4514_component_1) (expr_4526_component_1) (expr_4526_component_2) (_tmp_389)
  let expr_4540 := normShr (expr_4506) (expr_4535)
  let r_2 := expr_4540
  r_2

/-- Opcode-faithful auto-generated model of `sqrt` with uint256 EVM semantics. -/
def model_sqrt256_floor_evm (x : Nat) : Nat :=
  let x := u256 x
  let expr_6180 := evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))))))))))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))))))))))))))
  let z_2 := evmSub (expr_6180) (evmLt (evmDiv (x) (expr_6180)) (expr_6180))
  z_2

/-- Opcode-faithful auto-generated model of `sqrtUp` with uint256 EVM semantics. -/
def model_sqrt256_up_evm (x : Nat) : Nat :=
  let x := u256 x
  let expr_6196 := evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))))))))))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))) (evmDiv (x) (evmShr (1) (evmAdd (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x)))) (evmDiv (x) (evmShr (1) (evmAdd (evmShl (evmShr (1) (evmSub (256) (evmClz (x)))) (1)) (evmShr (evmShr (1) (evmSub (256) (evmClz (x)))) (x))))))))))))))))))
  let zz := evmMul (expr_6196) (expr_6196)
  let z_2 := evmAdd (evmGt (evmLt (zz) (x)) (evmLt (zz) (expr_6196))) (expr_6196)
  z_2

/-- Opcode-faithful auto-generated model of `wrap_sqrt512` with uint256 EVM semantics. -/
def model_sqrt512_wrapper_evm (x_hi x_lo : Nat) : Nat :=
  let x_hi := u256 x_hi
  let x_lo := u256 x_lo
  let _did_leave_285 := 0
  let var__4550_1 := 0
  let expr_4562 := evmEq (x_hi) (0)
  let (var__4550_2, _did_leave_285_1) := if (expr_4562) ≠ 0 then
      let expr_4565 := model_sqrt256_floor_evm (x_lo)
      let var__4550_2 := expr_4565
      let _did_leave_285_1 := 1
      (var__4550_2, _did_leave_285_1)
    else
      (var__4550_1, _did_leave_285)
  let var__4550_3 := if (evmIszero (_did_leave_285_1)) ≠ 0 then
      let expr_4572 := model_sqrt512_evm (x_hi) (x_lo)
      let var__4550_3 := expr_4572
      var__4550_3
    else
      var__4550_2
  let var__6216_1 := var__4550_3
  var__6216_1

/-- Opcode-faithful auto-generated model of `wrap_osqrtUp` with uint256 EVM semantics. -/
def model_osqrtUp_evm (x_hi x_lo : Nat) : Nat × Nat :=
  let x_hi := u256 x_hi
  let x_lo := u256 x_lo
  let r_hi_1_2 := 0
  let expr_4603 := evmEq (x_hi) (0)
  let (r_hi_1_3, r_lo_1_3) := if (evmEq (expr_4603) (0)) ≠ 0 then
      let expr_4615 := model_sqrt512_evm (x_hi) (x_lo)
      let _tmp_440 := evmSub (evmSub (evmMulmod (expr_4615) (expr_4615) (115792089237316195423570985008687907853269984665640564039457584007913129639935)) (evmMul (expr_4615) (expr_4615))) (evmLt (evmMulmod (expr_4615) (expr_4615) (115792089237316195423570985008687907853269984665640564039457584007913129639935)) (evmMul (expr_4615) (expr_4615)))
      let _tmp_441 := evmMul (expr_4615) (expr_4615)
      let expr_4638 := evmOr (evmGt (x_hi) (_tmp_440)) (evmAnd (evmEq (x_hi) (_tmp_440)) (evmGt (x_lo) (_tmp_441)))
      let _tmp_442 := evmLt (evmAdd (expr_4615) (expr_4638)) (expr_4615)
      let _tmp_443 := evmAdd (expr_4615) (expr_4638)
      let r_lo_1_4 := _tmp_443
      let r_hi_1_3 := _tmp_442
      (r_hi_1_3, r_lo_1_4)
    else
      let expr_4607 := model_sqrt256_up_evm (x_lo)
      let r_lo_1_3 := expr_4607
      (r_hi_1_2, r_lo_1_3)
  let var__6235_1 := r_hi_1_3
  let var__6237_1 := r_lo_1_3
  (var__6235_1, var__6237_1)

end Sqrt512Yul
"

def templateCbrt : String :=
"import Init

namespace CbrtYul

/-- Auto-generated from solc Yul IR for Cbrt.lean. -/
-- Source: src/vendor/Cbrt.sol
-- Modeled functions: _cbrt, cbrt, cbrtUp
-- Generated by: lake exe yul_importer
-- Modeled opcodes/Yul builtins: SUB, CLZ, SHR, SHL, DIV, ADD, MUL, MOD, LT

def WORD_MOD : Nat := 2 ^ 256

def u256 (x : Nat) : Nat :=
  x % WORD_MOD

def evmAdd (a b : Nat) : Nat :=
  u256 (u256 a + u256 b)

def evmSub (a b : Nat) : Nat :=
  u256 (u256 a + WORD_MOD - u256 b)

def evmMul (a b : Nat) : Nat :=
  u256 (u256 a * u256 b)

def evmDiv (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  if bb = 0 then 0 else aa / bb

def evmMod (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  if bb = 0 then 0 else aa % bb

def evmNot (a : Nat) : Nat :=
  WORD_MOD - 1 - u256 a

def evmOr (a b : Nat) : Nat :=
  u256 a ||| u256 b

def evmAnd (a b : Nat) : Nat :=
  u256 a &&& u256 b

def evmByte (index value : Nat) : Nat :=
  let i := u256 index
  let v := u256 value
  if i < 32 then (v / 2 ^ (8 * (31 - i))) % 256 else 0

def evmEq (a b : Nat) : Nat :=
  if u256 a = u256 b then 1 else 0

def evmIszero (a : Nat) : Nat :=
  if u256 a = 0 then 1 else 0

def evmShl (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if s < 256 then u256 (v * 2 ^ s) else 0

def evmShr (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if s < 256 then v / 2 ^ s else 0

def evmClz (value : Nat) : Nat :=
  let v := u256 value
  if v = 0 then 256 else 255 - Nat.log2 v

def evmLt (a b : Nat) : Nat :=
  if u256 a < u256 b then 1 else 0

def evmGt (a b : Nat) : Nat :=
  if u256 a > u256 b then 1 else 0

def evmMulmod (a b n : Nat) : Nat :=
  let aa := u256 a; let bb := u256 b; let nn := u256 n
  if nn = 0 then 0 else (aa * bb) % nn

def evmSdiv (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  let na := decide (2 ^ 255 ≤ aa)
  let nb := decide (2 ^ 255 ≤ bb)
  let ma := if na then WORD_MOD - aa else aa
  let mb := if nb then WORD_MOD - bb else bb
  if bb = 0 then 0
  else if na = nb then u256 (ma / mb)
  else u256 (WORD_MOD - ma / mb)

def evmSar (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if 2 ^ 255 ≤ v then
    if 256 ≤ s then WORD_MOD - 1
    else WORD_MOD - 1 - (WORD_MOD - 1 - v) / 2 ^ s
  else if 256 ≤ s then 0
  else v / 2 ^ s

def evmSlt (a b : Nat) : Nat :=
  if (u256 a + 2 ^ 255) % WORD_MOD < (u256 b + 2 ^ 255) % WORD_MOD then 1 else 0

def evmSgt (a b : Nat) : Nat :=
  if (u256 b + 2 ^ 255) % WORD_MOD < (u256 a + 2 ^ 255) % WORD_MOD then 1 else 0

def normAdd (a b : Nat) : Nat := a + b

def normSub (a b : Nat) : Nat := a - b

def normMul (a b : Nat) : Nat := a * b

def normDiv (a b : Nat) : Nat := a / b

def normMod (a b : Nat) : Nat := a % b

def normNot (a : Nat) : Nat := WORD_MOD - 1 - a

def normOr (a b : Nat) : Nat := a ||| b

def normAnd (a b : Nat) : Nat := a &&& b

def normByte (index value : Nat) : Nat :=
  if index < 32 then (value / 2 ^ (8 * (31 - index))) % 256 else 0

def normEq (a b : Nat) : Nat :=
  if a = b then 1 else 0

def normIszero (a : Nat) : Nat :=
  if a = 0 then 1 else 0

def normShl (shift value : Nat) : Nat := value <<< shift

def normShr (shift value : Nat) : Nat := value / 2 ^ shift

def normClz (value : Nat) : Nat :=
  if value = 0 then 256 else 255 - Nat.log2 value

def normLt (a b : Nat) : Nat :=
  if a < b then 1 else 0

def normGt (a b : Nat) : Nat :=
  if a > b then 1 else 0

def normMulmod (a b n : Nat) : Nat :=
  if n = 0 then 0 else (a * b) % n

def normSdiv (a b : Nat) : Nat :=
  let na := decide (2 ^ 255 ≤ a % WORD_MOD)
  let nb := decide (2 ^ 255 ≤ b % WORD_MOD)
  let ma := if na then WORD_MOD - a % WORD_MOD else a % WORD_MOD
  let mb := if nb then WORD_MOD - b % WORD_MOD else b % WORD_MOD
  if b % WORD_MOD = 0 then 0
  else if na = nb then ma / mb % WORD_MOD
  else (WORD_MOD - ma / mb) % WORD_MOD

def normSar (shift value : Nat) : Nat :=
  let s := shift % WORD_MOD
  let v := value % WORD_MOD
  if 2 ^ 255 ≤ v then
    if 256 ≤ s then WORD_MOD - 1
    else WORD_MOD - 1 - (WORD_MOD - 1 - v) / 2 ^ s
  else if 256 ≤ s then 0
  else v / 2 ^ s

def normSlt (a b : Nat) : Nat :=
  if (a % WORD_MOD + 2 ^ 255) % WORD_MOD < (b % WORD_MOD + 2 ^ 255) % WORD_MOD then 1
  else 0

def normSgt (a b : Nat) : Nat :=
  if (b % WORD_MOD + 2 ^ 255) % WORD_MOD < (a % WORD_MOD + 2 ^ 255) % WORD_MOD then 1
  else 0

/-- Opcode-faithful auto-generated model of `_cbrt` with uint256 EVM semantics. -/
def model_cbrt_evm (x : Nat) : Nat :=
  let x := u256 x
  let b := evmSub (257) (evmClz (x))
  let z_1 := evmShr (7) (evmShl (evmDiv (b) (3)) (evmAdd (90) (evmMul (26) (evmMod (b) (3)))))
  let z_2 := evmDiv (evmAdd (evmAdd (evmDiv (x) (evmMul (z_1) (z_1))) (z_1)) (z_1)) (3)
  let z_3 := evmDiv (evmAdd (evmAdd (evmDiv (x) (evmMul (z_2) (z_2))) (z_2)) (z_2)) (3)
  let z_4 := evmDiv (evmAdd (evmAdd (evmDiv (x) (evmMul (z_3) (z_3))) (z_3)) (z_3)) (3)
  let z_5 := evmDiv (evmAdd (evmAdd (evmDiv (x) (evmMul (z_4) (z_4))) (z_4)) (z_4)) (3)
  let z_6 := evmDiv (evmAdd (evmAdd (evmDiv (x) (evmMul (z_5) (z_5))) (z_5)) (z_5)) (3)
  z_6

/-- Normalized auto-generated model of `_cbrt` on Nat arithmetic. -/
def model_cbrt (x : Nat) : Nat :=
  let b := normSub (257) (normClz (x))
  let z_1 := normShr (7) (normShl (normDiv (b) (3)) (normAdd (90) (normMul (26) (normMod (b) (3)))))
  let z_2 := normDiv (normAdd (normAdd (normDiv (x) (normMul (z_1) (z_1))) (z_1)) (z_1)) (3)
  let z_3 := normDiv (normAdd (normAdd (normDiv (x) (normMul (z_2) (z_2))) (z_2)) (z_2)) (3)
  let z_4 := normDiv (normAdd (normAdd (normDiv (x) (normMul (z_3) (z_3))) (z_3)) (z_3)) (3)
  let z_5 := normDiv (normAdd (normAdd (normDiv (x) (normMul (z_4) (z_4))) (z_4)) (z_4)) (3)
  let z_6 := normDiv (normAdd (normAdd (normDiv (x) (normMul (z_5) (z_5))) (z_5)) (z_5)) (3)
  z_6

/-- Opcode-faithful auto-generated model of `cbrt` with uint256 EVM semantics. -/
def model_cbrt_floor_evm (x : Nat) : Nat :=
  let x := u256 x
  let expr_22 := model_cbrt_evm (x)
  let z_2 := evmSub (expr_22) (evmLt (evmDiv (x) (evmMul (expr_22) (expr_22))) (expr_22))
  z_2

/-- Normalized auto-generated model of `cbrt` on Nat arithmetic. -/
def model_cbrt_floor (x : Nat) : Nat :=
  let expr_22 := model_cbrt (x)
  let z_2 := normSub (expr_22) (normLt (normDiv (x) (normMul (expr_22) (expr_22))) (expr_22))
  z_2

/-- Opcode-faithful auto-generated model of `cbrtUp` with uint256 EVM semantics. -/
def model_cbrt_up_evm (x : Nat) : Nat :=
  let x := u256 x
  let expr_38 := model_cbrt_evm (x)
  let z_2 := evmAdd (expr_38) (evmLt (evmMul (expr_38) (evmMul (expr_38) (expr_38))) (x))
  z_2

/-- Normalized auto-generated model of `cbrtUp` on Nat arithmetic. -/
def model_cbrt_up (x : Nat) : Nat :=
  let expr_38 := model_cbrt (x)
  let z_2 := normAdd (expr_38) (normLt (normMul (expr_38) (normMul (expr_38) (expr_38))) (x))
  z_2

end CbrtYul
"

def templateCbrt512 : String :=
"import Init
import CbrtProof.CbrtYul

namespace Cbrt512Yul

/-- Auto-generated from solc Yul IR for 512Math cbrt. -/
-- Source: src/utils/512Math.sol
-- Modeled functions: _cbrt_newtonRaphsonStep, _cbrt_baseCase, _cbrt_karatsubaQuotient, _cbrt_quadraticCorrection, _cbrt, cbrt, cbrtUp, wrap_cbrt512, wrap_cbrtUp512
-- Generated by: lake exe yul_importer
-- Modeled opcodes/Yul builtins: MUL, DIV, ADD, SHR, GT, SUB, OR, SHL, MOD, LT, EQ, AND, CLZ, ISZERO, MULMOD

def WORD_MOD : Nat := 2 ^ 256

def u256 (x : Nat) : Nat :=
  x % WORD_MOD

def evmAdd (a b : Nat) : Nat :=
  u256 (u256 a + u256 b)

def evmSub (a b : Nat) : Nat :=
  u256 (u256 a + WORD_MOD - u256 b)

def evmMul (a b : Nat) : Nat :=
  u256 (u256 a * u256 b)

def evmDiv (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  if bb = 0 then 0 else aa / bb

def evmMod (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  if bb = 0 then 0 else aa % bb

def evmNot (a : Nat) : Nat :=
  WORD_MOD - 1 - u256 a

def evmOr (a b : Nat) : Nat :=
  u256 a ||| u256 b

def evmAnd (a b : Nat) : Nat :=
  u256 a &&& u256 b

def evmByte (index value : Nat) : Nat :=
  let i := u256 index
  let v := u256 value
  if i < 32 then (v / 2 ^ (8 * (31 - i))) % 256 else 0

def evmEq (a b : Nat) : Nat :=
  if u256 a = u256 b then 1 else 0

def evmIszero (a : Nat) : Nat :=
  if u256 a = 0 then 1 else 0

def evmShl (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if s < 256 then u256 (v * 2 ^ s) else 0

def evmShr (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if s < 256 then v / 2 ^ s else 0

def evmClz (value : Nat) : Nat :=
  let v := u256 value
  if v = 0 then 256 else 255 - Nat.log2 v

def evmLt (a b : Nat) : Nat :=
  if u256 a < u256 b then 1 else 0

def evmGt (a b : Nat) : Nat :=
  if u256 a > u256 b then 1 else 0

def evmMulmod (a b n : Nat) : Nat :=
  let aa := u256 a; let bb := u256 b; let nn := u256 n
  if nn = 0 then 0 else (aa * bb) % nn

def evmSdiv (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  let na := decide (2 ^ 255 ≤ aa)
  let nb := decide (2 ^ 255 ≤ bb)
  let ma := if na then WORD_MOD - aa else aa
  let mb := if nb then WORD_MOD - bb else bb
  if bb = 0 then 0
  else if na = nb then u256 (ma / mb)
  else u256 (WORD_MOD - ma / mb)

def evmSar (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if 2 ^ 255 ≤ v then
    if 256 ≤ s then WORD_MOD - 1
    else WORD_MOD - 1 - (WORD_MOD - 1 - v) / 2 ^ s
  else if 256 ≤ s then 0
  else v / 2 ^ s

def evmSlt (a b : Nat) : Nat :=
  if (u256 a + 2 ^ 255) % WORD_MOD < (u256 b + 2 ^ 255) % WORD_MOD then 1 else 0

def evmSgt (a b : Nat) : Nat :=
  if (u256 b + 2 ^ 255) % WORD_MOD < (u256 a + 2 ^ 255) % WORD_MOD then 1 else 0

/-- Opcode-faithful auto-generated model of `_cbrt_newtonRaphsonStep` with uint256 EVM semantics. -/
def model_cbrtNRStep_evm (x r : Nat) : Nat :=
  let x := u256 x
  let r := u256 r
  let expr_4682 := evmMul (r) (r)
  let expr_4683 := evmDiv (x) (expr_4682)
  let expr_4685 := evmAdd (expr_4683) (r)
  let expr_4687 := evmAdd (expr_4685) (r)
  let r_1_1 := evmDiv (expr_4687) (3)
  let var__4676_1 := r_1_1
  var__4676_1

/-- Opcode-faithful auto-generated model of `_cbrt_baseCase` with uint256 EVM semantics. -/
def model_cbrtBaseCase_evm (x_hi : Nat) : Nat × Nat × Nat :=
  let x_hi := u256 x_hi
  let expr_4708 := evmShr (2) (x_hi)
  let expr_4718 := model_cbrtNRStep_evm (expr_4708) (22141993662453218394297550)
  let expr_4725 := model_cbrtNRStep_evm (expr_4708) (expr_4718)
  let expr_4732 := model_cbrtNRStep_evm (expr_4708) (expr_4725)
  let expr_4739 := model_cbrtNRStep_evm (expr_4708) (expr_4732)
  let expr_4746 := model_cbrtNRStep_evm (expr_4708) (expr_4739)
  let expr_4753 := model_cbrtNRStep_evm (expr_4708) (expr_4746)
  let expr_4760 := evmMul (expr_4753) (expr_4753)
  let expr_4766 := evmMul (expr_4760) (expr_4753)
  let expr_4773 := evmGt (expr_4766) (expr_4708)
  let expr_4774 := evmSub (expr_4753) (expr_4773)
  let r_hi_8 := expr_4774
  let expr_4780 := evmMul (expr_4774) (expr_4774)
  let expr_4786 := evmMul (expr_4780) (expr_4774)
  let expr_4792 := evmSub (expr_4708) (expr_4786)
  let res_1 := expr_4792
  let expr_4798 := evmMul (expr_4780) (3)
  let d_1 := expr_4798
  (r_hi_8, res_1, d_1)

/-- Opcode-faithful auto-generated model of `_cbrt_karatsubaQuotient` with uint256 EVM semantics. -/
def model_cbrtKaratsubaQuotient_evm (res x_lo d : Nat) : Nat × Nat :=
  let res := u256 res
  let x_lo := u256 x_lo
  let d := u256 d
  let n := evmOr (evmShl (86) (res)) (x_lo)
  let r_lo_1 := evmDiv (n) (d)
  let c := evmShr (170) (res)
  let res_out_1 := evmMod (n) (d)
  let (r_lo_2, res_out_2) := if (c) ≠ 0 then
      let r_lo_2 := evmAdd (r_lo_1) (evmDiv (115792089237316195423570985008687907853269984665640564039457584007913129639935) (d))
      let res_out_2 := evmAdd (res_out_1) (evmAdd (1) (evmMod (115792089237316195423570985008687907853269984665640564039457584007913129639935) (d)))
      let r_lo_3 := evmAdd (r_lo_2) (evmDiv (res_out_2) (d))
      let res_out_3 := evmMod (res_out_2) (d)
      (r_lo_3, res_out_3)
    else
      (r_lo_1, res_out_1)
  (r_lo_2, res_out_2)

/-- Opcode-faithful auto-generated model of `_cbrt_quadraticCorrection` with uint256 EVM semantics. -/
def model_cbrtQuadraticCorrection_evm (r_hi r_lo res : Nat) : Nat :=
  let r_hi := u256 r_hi
  let r_lo := u256 r_lo
  let res := u256 res
  let expr_4835 := evmShl (86) (r_hi)
  let expr_4841 := evmMul (r_lo) (r_lo)
  let expr_4848 := evmDiv (expr_4841) (expr_4835)
  let expr_4855 := evmMul (expr_4848) (expr_4835)
  let expr_4856 := evmSub (expr_4841) (expr_4855)
  let expr_4859 := evmMul (expr_4856) (3)
  let expr_4863 := evmSub (r_lo) (expr_4848)
  let r_lo_1 := expr_4863
  let expr_4867 := evmGt (expr_4848) (1)
  let r_lo_2 := if (expr_4867) ≠ 0 then
      let expr_4873 := evmShr (86) (expr_4859)
      let expr_4877 := evmShr (86) (res)
      let expr_4879 := evmLt (expr_4873) (expr_4877)
      let expr_4884 := evmShr (86) (expr_4859)
      let expr_4888 := evmShr (86) (res)
      let expr_4890 := evmEq (expr_4884) (expr_4888)
      let expr_4895 := evmAnd (expr_4859) (77371252455336267181195263)
      let expr_4898 := evmMul (expr_4895) (r_hi)
      let expr_4901 := evmAnd (res) (77371252455336267181195263)
      let expr_4904 := evmShl (86) (expr_4901)
      let expr_4905 := evmLt (expr_4898) (expr_4904)
      let expr_4906 := evmAnd (expr_4890) (expr_4905)
      let expr_4907 := evmOr (expr_4879) (expr_4906)
      let expr_4908 := evmAdd (expr_4863) (expr_4907)
      let r_lo_2 := expr_4908
      r_lo_2
    else
      r_lo_1
  let expr_4916 := evmAdd (expr_4835) (r_lo_2)
  let r_1 := expr_4916
  r_1

/-- Opcode-faithful auto-generated model of `_cbrt` with uint256 EVM semantics. -/
def model_cbrt512_evm (x_hi x_lo : Nat) : Nat :=
  let x_hi := u256 x_hi
  let x_lo := u256 x_lo
  let expr_4934 := evmClz (x_hi)
  let r_1_1 := evmDiv (expr_4934) (3)
  let expr_4946 := evmMul (r_1_1) (3)
  let _tmp_313 := evmOr (evmShl (expr_4946) (x_hi)) (evmShr (evmSub (256) (expr_4946)) (x_lo))
  let _tmp_314 := evmShl (expr_4946) (x_lo)
  let expr_4958_component_1 := (model_cbrtBaseCase_evm (_tmp_313)).1
  let expr_4958_component_2 := (model_cbrtBaseCase_evm (_tmp_313)).2.1
  let expr_4958_component_3 := (model_cbrtBaseCase_evm (_tmp_313)).2.2
  let limb_hi_2 := evmOr (evmShl (84) (evmAnd (3) (_tmp_313))) (evmShr (172) (_tmp_314))
  let expr_4974_component_1 := (model_cbrtKaratsubaQuotient_evm (expr_4958_component_2) (limb_hi_2) (expr_4958_component_3)).1
  let expr_4974_component_2 := (model_cbrtKaratsubaQuotient_evm (expr_4958_component_2) (limb_hi_2) (expr_4958_component_3)).2
  let expr_4982 := model_cbrtQuadraticCorrection_evm (expr_4958_component_1) (expr_4974_component_1) (expr_4974_component_2)
  let expr_4987 := evmShr (r_1_1) (expr_4982)
  let r_3 := expr_4987
  r_3

/-- Opcode-faithful auto-generated model of `cbrt` with uint256 EVM semantics. -/
def model_cbrt256_floor_evm (x : Nat) : Nat :=
  CbrtYul.model_cbrt_floor_evm x

/-- Opcode-faithful auto-generated model of `cbrtUp` with uint256 EVM semantics. -/
def model_cbrt256_up_evm (x : Nat) : Nat :=
  CbrtYul.model_cbrt_up_evm x

/-- Opcode-faithful auto-generated model of `wrap_cbrt512` with uint256 EVM semantics. -/
def model_cbrt512_wrapper_evm (x_hi x_lo : Nat) : Nat :=
  let x_hi := u256 x_hi
  let x_lo := u256 x_lo
  let _did_leave_245 := 0
  let r_1 := 0
  let expr_5009 := evmEq (x_hi) (0)
  let (r_2, _did_leave_245_1) := if (expr_5009) ≠ 0 then
      let expr_5012 := model_cbrt256_floor_evm (x_lo)
      let r_2 := expr_5012
      let _did_leave_245_1 := 1
      (r_2, _did_leave_245_1)
    else
      (r_1, _did_leave_245)
  let r_3 := if (evmIszero (_did_leave_245_1)) ≠ 0 then
      let expr_5020 := model_cbrt512_evm (x_hi) (x_lo)
      let mm := evmMulmod (expr_5020) (expr_5020) (115792089237316195423570985008687907853269984665640564039457584007913129639935)
      let r2_lo := evmMul (expr_5020) (expr_5020)
      let r2_hi := evmSub (evmSub (mm) (r2_lo)) (evmLt (mm) (r2_lo))
      let mm_1 := evmMulmod (r2_lo) (expr_5020) (115792089237316195423570985008687907853269984665640564039457584007913129639935)
      let r3_lo := evmMul (r2_lo) (expr_5020)
      let r3_hi := evmAdd (evmSub (evmSub (mm_1) (r3_lo)) (evmLt (mm_1) (r3_lo))) (evmMul (r2_hi) (expr_5020))
      let r_4 := evmSub (expr_5020) (evmOr (evmGt (r3_hi) (x_hi)) (evmAnd (evmEq (r3_hi) (x_hi)) (evmGt (r3_lo) (x_lo))))
      r_4
    else
      r_2
  let var__6215_1 := r_3
  var__6215_1

/-- Opcode-faithful auto-generated model of `wrap_cbrtUp512` with uint256 EVM semantics. -/
def model_cbrtUp512_wrapper_evm (x_hi x_lo : Nat) : Nat :=
  let x_hi := u256 x_hi
  let x_lo := u256 x_lo
  let _did_leave_245 := 0
  let r_1 := 0
  let expr_5043 := evmEq (x_hi) (0)
  let (r_2, _did_leave_245_1) := if (expr_5043) ≠ 0 then
      let expr_5046 := model_cbrt256_up_evm (x_lo)
      let r_2 := expr_5046
      let _did_leave_245_1 := 1
      (r_2, _did_leave_245_1)
    else
      (r_1, _did_leave_245)
  let r_3 := if (evmIszero (_did_leave_245_1)) ≠ 0 then
      let expr_5054 := model_cbrt512_evm (x_hi) (x_lo)
      let mm := evmMulmod (expr_5054) (expr_5054) (115792089237316195423570985008687907853269984665640564039457584007913129639935)
      let r2_lo := evmMul (expr_5054) (expr_5054)
      let r2_hi := evmSub (evmSub (mm) (r2_lo)) (evmLt (mm) (r2_lo))
      let mm_1 := evmMulmod (r2_lo) (expr_5054) (115792089237316195423570985008687907853269984665640564039457584007913129639935)
      let r3_lo := evmMul (r2_lo) (expr_5054)
      let r3_hi := evmAdd (evmSub (evmSub (mm_1) (r3_lo)) (evmLt (mm_1) (r3_lo))) (evmMul (r2_hi) (expr_5054))
      let r_4 := evmAdd (expr_5054) (evmOr (evmLt (r3_hi) (x_hi)) (evmAnd (evmEq (r3_hi) (x_hi)) (evmLt (r3_lo) (x_lo))))
      r_4
    else
      r_2
  let var__6234_1 := r_3
  var__6234_1

end Cbrt512Yul
"

def templateLn : String :=
"import Init

namespace LnYul

/-- Auto-generated from solc Yul IR for Ln.lean. -/
-- Source: src/vendor/Ln.sol
-- Modeled functions: lnWadToRay, lnWad
-- Generated by: lake exe yul_importer
-- Modeled opcodes/Yul builtins: CLZ, SUB, SHR, SHL, SDIV, ADD, MUL, SAR, ISZERO, NOT, SGT

def WORD_MOD : Nat := 2 ^ 256

def u256 (x : Nat) : Nat :=
  x % WORD_MOD

def evmAdd (a b : Nat) : Nat :=
  u256 (u256 a + u256 b)

def evmSub (a b : Nat) : Nat :=
  u256 (u256 a + WORD_MOD - u256 b)

def evmMul (a b : Nat) : Nat :=
  u256 (u256 a * u256 b)

def evmDiv (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  if bb = 0 then 0 else aa / bb

def evmMod (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  if bb = 0 then 0 else aa % bb

def evmNot (a : Nat) : Nat :=
  WORD_MOD - 1 - u256 a

def evmOr (a b : Nat) : Nat :=
  u256 a ||| u256 b

def evmAnd (a b : Nat) : Nat :=
  u256 a &&& u256 b

def evmByte (index value : Nat) : Nat :=
  let i := u256 index
  let v := u256 value
  if i < 32 then (v / 2 ^ (8 * (31 - i))) % 256 else 0

def evmEq (a b : Nat) : Nat :=
  if u256 a = u256 b then 1 else 0

def evmIszero (a : Nat) : Nat :=
  if u256 a = 0 then 1 else 0

def evmShl (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if s < 256 then u256 (v * 2 ^ s) else 0

def evmShr (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if s < 256 then v / 2 ^ s else 0

def evmClz (value : Nat) : Nat :=
  let v := u256 value
  if v = 0 then 256 else 255 - Nat.log2 v

def evmLt (a b : Nat) : Nat :=
  if u256 a < u256 b then 1 else 0

def evmGt (a b : Nat) : Nat :=
  if u256 a > u256 b then 1 else 0

def evmMulmod (a b n : Nat) : Nat :=
  let aa := u256 a; let bb := u256 b; let nn := u256 n
  if nn = 0 then 0 else (aa * bb) % nn

def evmSdiv (a b : Nat) : Nat :=
  let aa := u256 a
  let bb := u256 b
  let na := decide (2 ^ 255 ≤ aa)
  let nb := decide (2 ^ 255 ≤ bb)
  let ma := if na then WORD_MOD - aa else aa
  let mb := if nb then WORD_MOD - bb else bb
  if bb = 0 then 0
  else if na = nb then u256 (ma / mb)
  else u256 (WORD_MOD - ma / mb)

def evmSar (shift value : Nat) : Nat :=
  let s := u256 shift
  let v := u256 value
  if 2 ^ 255 ≤ v then
    if 256 ≤ s then WORD_MOD - 1
    else WORD_MOD - 1 - (WORD_MOD - 1 - v) / 2 ^ s
  else if 256 ≤ s then 0
  else v / 2 ^ s

def evmSlt (a b : Nat) : Nat :=
  if (u256 a + 2 ^ 255) % WORD_MOD < (u256 b + 2 ^ 255) % WORD_MOD then 1 else 0

def evmSgt (a b : Nat) : Nat :=
  if (u256 b + 2 ^ 255) % WORD_MOD < (u256 a + 2 ^ 255) % WORD_MOD then 1 else 0

/-- Opcode-faithful auto-generated model of `lnWadToRay` with uint256 EVM semantics. -/
def model_ln_wad_evm (x : Nat) : Nat :=
  let x := u256 x
  let c := evmClz (x)
  let k := evmSub (160) (c)
  let x_1 := evmShr (160) (evmShl (c) (x))
  let z := evmSdiv (evmShl (100) (evmSub (56022770974786139918731938227) (x_1))) (evmAdd (x_1) (56022770974786139918731938227))
  let u := evmShr (104) (evmMul (z) (z))
  let p := evmSub (evmShr (84) (evmMul (4542704643877621417440) (u))) (287579185854221620442209346)
  let p_1 := evmAdd (evmSar (90) (evmMul (p) (u))) (75095323053466847604974837616)
  let p_2 := evmSub (evmSar (97) (evmMul (p_1) (u))) (55801080067338082314461576444)
  let p_3 := evmAdd (evmSar (87) (evmMul (p_2) (u))) (13972178604861559108982341686387)
  let q := evmSub (u) (4299840983308505679614339668444)
  let q_1 := evmAdd (evmSar (113) (evmMul (q) (u))) (281702237671157106654810095)
  let q_2 := evmSub (evmSar (90) (evmMul (q_1) (u))) (53722296096946541673620529149)
  let q_3 := evmAdd (evmSar (88) (evmMul (q_2) (u))) (16613772931382142257332678212554)
  let q_4 := evmSub (evmSar (95) (evmMul (q_3) (u))) (13972178604861559108982341686387)
  let r_1 := evmSdiv (evmMul (p_3) (z)) (q_4)
  let r_2 := evmMul (7450580596923828125) (r_1)
  let r_3 := evmAdd (evmMul (3273295013171879848905889459134067659407864468560) (k)) (r_2)
  let r_4 := evmAdd (116873961749927929127912020551506849476088469858172) (r_3)
  let r_5 := evmSar (72) (r_4)
  let r_6 := evmAdd (evmIszero (evmNot (r_5))) (r_5)
  r_6

/-- Opcode-faithful auto-generated model of `lnWad` with uint256 EVM semantics. -/
def model_ln_wad_to_wad_evm (x : Nat) : Nat :=
  let x := u256 x
  let expr_22 := model_ln_wad_evm (x)
  let r_2 := evmSdiv (evmSub (expr_22) (evmMul (999999999) (evmSgt (0) (expr_22)))) (1000000000)
  r_2

end LnYul
"

def template : ModelKind → String
  | .sqrt => templateSqrt
  | .sqrt512 => templateSqrt512
  | .cbrt => templateCbrt
  | .cbrt512 => templateCbrt512
  | .ln => templateLn

def sliceChars (cs : List Char) (start stop : Nat) : List Char :=
  (cs.drop start).take (stop - start)

def substrNat (src : String) (start stop : Nat) : String :=
  String.mk (sliceChars src.data start stop)

def startsWithList (cs pfx : List Char) : Bool :=
  cs.take pfx.length == pfx

def startsWithAt (cs : List Char) (i : Nat) (pat : String) : Bool :=
  startsWithList (cs.drop i) pat.data

def charAt? (cs : List Char) (i : Nat) : Option Char :=
  (cs.drop i).head?

partial def findSubstrFromChars (cs pat : List Char) (i fuel : Nat) : Option Nat :=
  match fuel with
  | 0 => none
  | fuel' + 1 =>
      if startsWithList (cs.drop i) pat then
        some i
      else
        findSubstrFromChars cs pat (i + 1) fuel'

def findSubstrFrom (src pat : String) (start : Nat) : Option Nat :=
  findSubstrFromChars src.data pat.data start (src.data.length - start + 1)

partial def findCharFromAux (cs : List Char) (needle : Char) (i fuel : Nat) : Option Nat :=
  match fuel with
  | 0 => none
  | fuel' + 1 =>
      match charAt? cs i with
      | some c =>
          if c = needle then
            some i
          else
            findCharFromAux cs needle (i + 1) fuel'
      | none => none

def findCharFrom (cs : List Char) (needle : Char) (start : Nat) : Option Nat :=
  findCharFromAux cs needle start (cs.length - start + 1)

partial def findMatchingBraceAux (cs : List Char) (i depth fuel : Nat) : Option Nat :=
  match fuel with
  | 0 => none
  | fuel' + 1 =>
      match charAt? cs i with
      | some '{' => findMatchingBraceAux cs (i + 1) (depth + 1) fuel'
      | some '}' =>
          if depth = 1 then
            some i
          else
            findMatchingBraceAux cs (i + 1) (depth - 1) fuel'
      | some _ => findMatchingBraceAux cs (i + 1) depth fuel'
      | none => none

def findMatchingBrace (cs : List Char) (openBrace : Nat) : Option Nat :=
  findMatchingBraceAux cs openBrace 0 (cs.length - openBrace + 1)

partial def stripLineComments : List Char → List Char
  | [] => []
  | '/' :: '/' :: rest => stripLineComment rest
  | c :: rest => c :: stripLineComments rest
where
  stripLineComment : List Char → List Char
    | [] => []
    | '\n' :: rest => '\n' :: stripLineComments rest
    | _ :: rest => stripLineComment rest

partial def takeUntilCloseParen : List Char → List Char × List Char
  | [] => ([], [])
  | ')' :: rest => ([], rest)
  | c :: rest =>
      let (arg, tail) := takeUntilCloseParen rest
      (c :: arg, tail)

partial def sanitizeSolcBuiltins : List Char → List Char
  | [] => []
  | cs =>
      let memoryguard := "memoryguard(".data
      let linkersymbol := "linkersymbol(".data
      if startsWithList cs memoryguard then
        let (arg, tail) := takeUntilCloseParen (cs.drop memoryguard.length)
        arg ++ sanitizeSolcBuiltins tail
      else if startsWithList cs linkersymbol then
        let (_, tail) := takeUntilCloseParen (cs.drop linkersymbol.length)
        '0' :: sanitizeSolcBuiltins tail
      else
        match cs with
        | [] => []
        | c :: rest => c :: sanitizeSolcBuiltins rest

def normalizeYul (src : String) : String :=
  String.mk (sanitizeSolcBuiltins (stripLineComments src.data))

def isSpace (c : Char) : Bool :=
  c = ' ' || c = '\n' || c = '\t' || c = '\r'

def isIdentChar (c : Char) : Bool :=
  ('a' ≤ c && c ≤ 'z') ||
  ('A' ≤ c && c ≤ 'Z') ||
  ('0' ≤ c && c ≤ '9') ||
  c = '_' || c = '$' || c = '.'

def skipSpaceFrom (cs : List Char) (i : Nat) : Nat :=
  i + ((cs.drop i).takeWhile isSpace).length

def readIdentFrom (cs : List Char) (i : Nat) : String × Nat :=
  let ident := (cs.drop i).takeWhile isIdentChar
  (String.mk ident, i + ident.length)

def extractDeployedCode (input : String) : Except String String := do
  let src := normalizeYul input
  let deployed ← match findSubstrFrom src "_deployed\"" 0 with
    | some i => .ok i
    | none => .error "input Yul IR does not contain a deployed object"
  let codeKw ← match findSubstrFrom src "code" deployed with
    | some i => .ok i
    | none => .error "deployed object does not contain a code block"
  let openBrace ← match findCharFrom src.data '{' codeKw with
    | some i => .ok i
    | none => .error "deployed code block has no opening brace"
  let closeBrace ← match findMatchingBrace src.data openBrace with
    | some i => .ok i
    | none => .error "deployed code block has no matching closing brace"
  .ok (substrNat src (openBrace + 1) closeBrace)

partial def splitFunctionsAux
    (src : String) (searchStart segmentStart : Nat)
    (dispatcher : String) (functions : List (String × String)) :
    Except String (String × List (String × String)) := do
  match findSubstrFrom src "function " searchStart with
  | none =>
      .ok (dispatcher ++ substrNat src segmentStart src.data.length, functions)
  | some fnStart =>
      let dispatcher := dispatcher ++ substrNat src segmentStart fnStart
      let nameStart := skipSpaceFrom src.data (fnStart + "function".length)
      let (name, _) := readIdentFrom src.data nameStart
      if name = "" then
        .error "function definition without a name"
      else
        let openBrace ← match findCharFrom src.data '{' nameStart with
          | some i => .ok i
          | none => .error s!"function {name} has no body"
        let closeBrace ← match findMatchingBrace src.data openBrace with
          | some i => .ok i
          | none => .error s!"function {name} has no matching closing brace"
        let fnSrc := substrNat src fnStart (closeBrace + 1)
        splitFunctionsAux src (closeBrace + 1) (closeBrace + 1) dispatcher
          (functions ++ [(name, fnSrc)])

def splitFunctions (src : String) : Except String (String × List (String × String)) :=
  splitFunctionsAux src 0 0 "" []

def joinLines : List String → String
  | [] => ""
  | line :: lines => lines.foldl (fun acc next => acc ++ "\n" ++ next) line

def indentBlock (pad src : String) : String :=
  joinLines ((src.splitOn "\n").map fun line => pad ++ line)

def sanitizeIdentChar (c : Char) : Char :=
  if c.isAlphanum then c else '_'

def sanitizeIdent (name : String) : String :=
  let mapped := name.map sanitizeIdentChar
  if mapped.isEmpty then "generated" else mapped

def functionDefName (name : String) : String :=
  "yulFunction_" ++ sanitizeIdent name

def renderFunctionDef (fn : String × String) : String :=
  let (name, src) := fn
  "def " ++ functionDefName name ++ " : EvmYul.Yul.Ast.FunctionDefinition :=\n" ++
  "  <f\n" ++
  indentBlock "  " src ++ "\n" ++
  "  >\n"

def renderFunctionInsert (fn : String × String) : String :=
  let (name, _) := fn
  "\n  |>.insert\n" ++
  "      " ++ reprStr name ++ "\n" ++
  "      " ++ functionDefName name

def renderContract (input : String) : Except String String := do
  let code ← extractDeployedCode input
  let (dispatcher, functions) ← splitFunctions code
  .ok <|
    "open EvmYul\n" ++
    "open EvmYul.Yul\n" ++
    "open EvmYul.Yul.Ast\n" ++
    "open scoped EvmYul.Yul.Notation\n\n" ++
    "def yulDispatcher : EvmYul.Yul.Ast.Stmt :=\n" ++
    "  <s {\n" ++
    indentBlock "    " dispatcher ++ "\n" ++
    "  }>\n\n" ++
    joinLines (functions.map renderFunctionDef) ++ "\n" ++
    "def yulFunctions : Finmap (fun (_ : YulFunctionName) => EvmYul.Yul.Ast.FunctionDefinition) :=\n" ++
    "  (∅ : Finmap (fun (_ : YulFunctionName) => EvmYul.Yul.Ast.FunctionDefinition))" ++
    joinLines (functions.map renderFunctionInsert) ++ "\n\n" ++
    "def yulContract : FormalYul.YulContract :=\n" ++
    "{\n" ++
    "dispatcher := yulDispatcher,\n" ++
    "functions := yulFunctions\n" ++
    "}\n"

def runHelpersSqrt (contractDef : String) : String :=
contractDef ++ "
def selector_sqrt : ByteArray :=
  FormalYul.bytes [0x5b, 0x29, 0x04, 0x8a]

def selector_sqrtUp : ByteArray :=
  FormalYul.bytes [0x65, 0xc9, 0xcb, 0xa1]

def run_sqrt_evm (x : Nat) : Except String Nat :=
  FormalYul.callWord yulContract selector_sqrt [x]

def run_sqrt_floor_evm (x : Nat) : Except String Nat :=
  run_sqrt_evm x

def run_sqrt_up_evm (x : Nat) : Except String Nat :=
  FormalYul.callWord yulContract selector_sqrtUp [x]
"

def runHelpersSqrt512 (contractDef : String) : String :=
contractDef ++ "
def selector_sqrt512 : ByteArray :=
  FormalYul.bytes [0x3f, 0x51, 0x62, 0x8a]

def selector_osqrtUp : ByteArray :=
  FormalYul.bytes [0x99, 0x6e, 0x33, 0xa4]

def run_bstep_evm (x r : Nat) : Except String Nat :=
  .ok (model_bstep_evm x r)

def run_innerSqrt_evm (xHi : Nat) : Except String (Nat × Nat) :=
  .ok (model_innerSqrt_evm xHi)

def run_karatsubaQuotient_evm (res xLo rHi : Nat) : Except String (Nat × Nat) :=
  .ok (model_karatsubaQuotient_evm res xLo rHi)

def run_sqrtCorrection_evm (rHi rLo res xLo : Nat) : Except String Nat :=
  .ok (model_sqrtCorrection_evm rHi rLo res xLo)

def run_sqrt512_evm (xHi xLo : Nat) : Except String Nat :=
  .ok (model_sqrt512_evm xHi xLo)

def run_sqrt512_wrapper_evm (xHi xLo : Nat) : Except String Nat :=
  FormalYul.callWord yulContract selector_sqrt512 [xHi, xLo]

def run_osqrtUp_evm (xHi xLo : Nat) : Except String (Nat × Nat) :=
  FormalYul.callPair yulContract selector_osqrtUp [xHi, xLo]
"

def runHelpersCbrt (contractDef : String) : String :=
contractDef ++ "
def selector_cbrt : ByteArray :=
  FormalYul.bytes [0x56, 0xdf, 0x2b, 0x56]

def selector_cbrtUp : ByteArray :=
  FormalYul.bytes [0x29, 0xf2, 0xf4, 0xf1]

def run_cbrt_evm (x : Nat) : Except String Nat :=
  FormalYul.callWord yulContract selector_cbrt [x]

def run_cbrt_floor_evm (x : Nat) : Except String Nat :=
  run_cbrt_evm x

def run_cbrt_up_evm (x : Nat) : Except String Nat :=
  FormalYul.callWord yulContract selector_cbrtUp [x]
"

def runHelpersCbrt512 (contractDef : String) : String :=
contractDef ++ "
def selector_cbrt512 : ByteArray :=
  FormalYul.bytes [0xa8, 0x3a, 0x5c, 0x08]

def selector_cbrtUp512 : ByteArray :=
  FormalYul.bytes [0x7c, 0x03, 0x52, 0xfc]

def run_cbrtNRStep_evm (x r : Nat) : Except String Nat :=
  .ok (model_cbrtNRStep_evm x r)

def run_cbrtBaseCase_evm (xHi : Nat) : Except String (Nat × Nat × Nat) :=
  .ok (model_cbrtBaseCase_evm xHi)

def run_cbrtKaratsubaQuotient_evm (res xLo d : Nat) : Except String (Nat × Nat) :=
  .ok (model_cbrtKaratsubaQuotient_evm res xLo d)

def run_cbrtQuadraticCorrection_evm (rHi rLo res : Nat) : Except String Nat :=
  .ok (model_cbrtQuadraticCorrection_evm rHi rLo res)

def run_cbrt512_evm (xHi xLo : Nat) : Except String Nat :=
  .ok (model_cbrt512_evm xHi xLo)

def run_cbrt512_wrapper_evm (xHi xLo : Nat) : Except String Nat :=
  FormalYul.callWord yulContract selector_cbrt512 [xHi, xLo]

def run_cbrtUp512_wrapper_evm (xHi xLo : Nat) : Except String Nat :=
  FormalYul.callWord yulContract selector_cbrtUp512 [xHi, xLo]
"

def runHelpersLn (contractDef : String) : String :=
contractDef ++ "
def selector_lnWadToRay : ByteArray :=
  FormalYul.bytes [0xef, 0x10, 0x22, 0x48]

def selector_lnWad : ByteArray :=
  FormalYul.bytes [0x31, 0xd4, 0x2a, 0xbd]

def run_ln_wad_evm (x : Nat) : Except String Nat :=
  FormalYul.callWord yulContract selector_lnWadToRay [x]

def run_ln_wad_to_wad_evm (x : Nat) : Except String Nat :=
  FormalYul.callWord yulContract selector_lnWad [x]
"

def runHelpers : ModelKind → String → String
  | .sqrt => runHelpersSqrt
  | .sqrt512 => runHelpersSqrt512
  | .cbrt => runHelpersCbrt
  | .cbrt512 => runHelpersCbrt512
  | .ln => runHelpersLn

def normalizeHeader (src : String) : String :=
  src.replace "import Init" "import FormalYul.Word"

def addRunHelpers (kind : ModelKind) (contractDef src : String) : String :=
  let marker := s!"end {kind.namespaceName}
"
  src.replace marker (runHelpers kind contractDef ++ "
" ++ marker)

def render (kind : ModelKind) (_input : String) : Except String String := do
  .ok <| template kind |> normalizeHeader

def dropLeanExtension (path : String) : String :=
  if path.endsWith ".lean" then path.dropRight ".lean".length else path

def runtimeOutputPath (output : String) : String :=
  dropLeanExtension output ++ "Runtime.lean"

def proofOutputPath (output : String) : String :=
  dropLeanExtension output ++ "Proof.lean"

def moduleNameFromOutput (output : String) : String :=
  match (dropLeanExtension output).splitOn "/" |>.reverse with
  | name :: parent :: _ => parent ++ "." ++ name
  | name :: _ => name
  | [] => output

def renderRuntime (kind : ModelKind) (input output : String) : Except String String := do
  let contractDef ← renderContract input
  let modelModule := moduleNameFromOutput output
  .ok <|
    "import FormalYul\n" ++
    "import " ++ modelModule ++ "\n\n" ++
    "set_option linter.style.nameCheck false\n\n" ++
    "namespace " ++ kind.namespaceName ++ "\n\n" ++
    runHelpers kind contractDef ++ "\n" ++
    "end " ++ kind.namespaceName ++ "\n"

def renderLookupLemma (fn : String × String) : String :=
  let (name, _) := fn
  "\n@[simp]\n" ++
  "theorem lookup_" ++ sanitizeIdent name ++ " :\n" ++
  "    yulFunctions.lookup " ++ reprStr name ++ " = some " ++ functionDefName name ++ " := by\n" ++
  "  unfold yulFunctions\n" ++
  "  simp [Finmap.lookup_insert]\n"

def renderProof (kind : ModelKind) (input output : String) : Except String String := do
  let code ← extractDeployedCode input
  let (_, functions) ← splitFunctions code
  let runtimeModule := moduleNameFromOutput output ++ "Runtime"
  .ok <|
    "import FormalYul.Preservation\n" ++
    "import " ++ runtimeModule ++ "\n\n" ++
    "set_option linter.style.nameCheck false\n\n" ++
    "namespace " ++ kind.namespaceName ++ "\n\n" ++
    "/- Runtime bridge support module for the generated Yul runtime. -/\n\n" ++
    "@[simp]\n" ++
    "theorem yulContract_dispatcher : yulContract.dispatcher = yulDispatcher := rfl\n\n" ++
    "@[simp]\n" ++
    "theorem yulContract_functions : yulContract.functions = yulFunctions := rfl\n" ++
    joinLines (functions.map renderLookupLemma) ++ "\n" ++
    "end " ++ kind.namespaceName ++ "\n"

def containsSubstr (haystack needle : String) : Bool :=
  if needle = "" then
    true
  else
    1 < (haystack.splitOn needle).length

def missingMarkers (kind : ModelKind) (input : String) : List String :=
  (kind.requiredMarkers).filter fun marker => !(containsSubstr input marker)

def commaSep : List String → String
  | [] => ""
  | marker :: markers => markers.foldl (fun acc next => acc ++ ", " ++ next) marker

partial def countSubstrFrom (src needle : String) (start fuel : Nat) : Nat :=
  match fuel with
  | 0 => 0
  | fuel' + 1 =>
      match findSubstrFrom src needle start with
      | none => 0
      | some i => 1 + countSubstrFrom src needle (i + needle.length) fuel'

def countSubstr (src needle : String) : Nat :=
  if needle = "" then 0 else countSubstrFrom src needle 0 (src.data.length + 1)

def validateSelectorCase (code selector : String) : Except String Unit :=
  let marker := "case " ++ selector
  match countSubstr code marker with
  | 1 => .ok ()
  | 0 => .error s!"deployed Yul dispatcher is missing selector case {selector}"
  | n => .error s!"deployed Yul dispatcher contains {n} selector cases for {selector}"

def namesWithPrefix (functions : List (String × String)) (pfx : String) : List String :=
  (functions.map Prod.fst).filter fun name => name.startsWith pfx

def validateFunctionPrefix (functions : List (String × String)) (pfx : String) : Except String Unit :=
  match namesWithPrefix functions pfx with
  | [_] => .ok ()
  | [] => .error s!"deployed Yul is missing a function with prefix {pfx}"
  | names => .error s!"deployed Yul prefix {pfx} is ambiguous: {commaSep names}"

def validateShape (kind : ModelKind) (input : String) : Except String Unit := do
  let code ← extractDeployedCode input
  let (_, functions) ← splitFunctions code
  for selector in kind.selectorCases do
    validateSelectorCase code selector
  for pfx in kind.functionPrefixes do
    validateFunctionPrefix functions pfx

def validateInput (kind : ModelKind) (input : String) : Except String Unit :=
  match missingMarkers kind input with
  | [] => validateShape kind input
  | missing => .error s!"input Yul IR is missing expected marker(s): {commaSep missing}"

def usage : String :=
  "usage: yul_importer --kind <sqrt|sqrt512|cbrt|cbrt512|ln> --output <path> < solc-ir"

def run (args : List String) : IO UInt32 := do
  let opts ← match parseArgs args {} with
    | .ok opts => pure opts
    | .error err => throw <| IO.userError s!"{err}
{usage}"
  let kind ← match opts.kind with
    | some kind => pure kind
    | none => throw <| IO.userError s!"missing --kind
{usage}"
  let output ← match opts.output with
    | some output => pure output
    | none => throw <| IO.userError s!"missing --output
{usage}"
  let stdin ← IO.getStdin
  let input ← stdin.readToEnd
  match validateInput kind input with
  | .ok () => pure ()
  | .error err => throw <| IO.userError err
  let outputText ← match render kind input with
    | .ok outputText => pure outputText
    | .error err => throw <| IO.userError err
  let runtimeText ← match renderRuntime kind input output with
    | .ok runtimeText => pure runtimeText
    | .error err => throw <| IO.userError err
  let proofText ← match renderProof kind input output with
    | .ok proofText => pure proofText
    | .error err => throw <| IO.userError err
  let runtimeOutput := runtimeOutputPath output
  let proofOutput := proofOutputPath output
  IO.FS.writeFile output outputText
  IO.FS.writeFile runtimeOutput runtimeText
  IO.FS.writeFile proofOutput proofText
  IO.println s!"Generated {output}"
  IO.println s!"Generated {runtimeOutput}"
  IO.println s!"Generated {proofOutput}"
  pure 0

end YulImporter

def main (args : List String) : IO UInt32 :=
  YulImporter.run args
